name: Test
on: [push, pull_request]

jobs:
  lint-build:
    name: Lint and Build
    runs-on: ubuntu-latest
    env:
      FIREBASE_API_KEY: ${{secrets.FIREBASE_API_KEY}}
      FIREBASE_AUTH_DOMAIN: ${{secrets.FIREBASE_AUTH_DOMAIN}}
      FIREBASE_PROJECT_ID: ${{secrets.FIREBASE_PROJECT_ID}}
      FIREBASE_STORAGE_BUCKET: ${{secrets.FIREBASE_STORAGE_BUCKET}}
      FIREBASE_SENDER_ID: ${{secrets.FIREBASE_SENDER_ID}}
      FIREBASE_API_ID: ${{secrets.FIREBASE_API_ID}}
      FIREBASE_MEASUREMENT_ID: ${{secrets.FIREBASE_MEASUREMENT_ID}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint --max-warnings=0

      - name: Build
        run: yarn build

      - name: Audit
        run: yarn audit

  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      FIREBASE_API_KEY: ${{secrets.FIREBASE_API_KEY}}
      FIREBASE_AUTH_DOMAIN: ${{secrets.FIREBASE_AUTH_DOMAIN}}
      FIREBASE_PROJECT_ID: ${{secrets.FIREBASE_PROJECT_ID}}
      FIREBASE_STORAGE_BUCKET: ${{secrets.FIREBASE_STORAGE_BUCKET}}
      FIREBASE_SENDER_ID: ${{secrets.FIREBASE_SENDER_ID}}
      FIREBASE_API_ID: ${{secrets.FIREBASE_API_ID}}
      FIREBASE_MEASUREMENT_ID: ${{secrets.FIREBASE_MEASUREMENT_ID}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Unit Test
        run: yarn test

      - name: E2E Test
        run: yarn test:e2e
